vich_uploader:
    db_driver: orm

    mappings:
        products:
            uri_prefix: /images/gundams
            upload_destination: '%kernel.project_dir%/public/images/gundams'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
